[package]
name = "clockwise-testbed"
version = "0.1.0"
authors = ["Marshall Clyburn"]
edition = "2018"

[dependencies]
clockwise_common = { path = "../common" }
clockwise_shared = { path = "../shared" }

getopts = "^0.2"
libloading = "^0.7"
rppal = "^0.11"
